metadata:
  artist: Artist Name 1 (and his mate)
  album: Album Made With My Mate
  year: 2004

# This album is rubbish; we don't want it on our devices
# outputs:
#   phone:
#     enabled: true
#     opus_bitrate: 96k
